export const data = [
  {
      "name": "2001: A Space Odyssey",
      "img": "https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png",
      "director": "Stanley Kubrick",
      "actors": ["Keir Dullea", "Gary Lockwood", "Hal 9000", "William Sylvester"],
      "imdb_point": 8.3,
  },
  {
      "name": "Blade Runner",
      "img": "https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png",
      "director": "Ridley Scott",
      "actors": ["Harrison Ford", "Rutger Hauer", "Sean Young", "Edward James Olmos"],
      "imdb_point": 8.1,
  },
  {
      "name": "Star Wars: Episode IV - A New Hope",
      "img": "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg",
      "director": "George Lucas",
      "actors": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
      "imdb_point": 8.6,
  },
  {
      "name": "Alien",
      "img": "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg",
      "director": "Ridley Scott",
      "actors": ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Veronica Cartwright"],
      "imdb_point": 8.4,
  },
  {
      "name": "E.T. the Extra-Terrestrial",
      "img": "https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg",
      "director": "Steven Spielberg",
      "actors": ["Henry Thomas", "Drew Barrymore", "Dee Wallace", "Peter Coyote"],
      "imdb_point": 7.8,
  },
  {
      "name": "Back to the Future",
      "img": "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
      "director": "Robert Zemeckis",
      "actors": ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
      "imdb_point": 8.5,
  },
  {
      "name": "Terminator 2: Judgment Day",
      "img": "https://upload.wikimedia.org/wikipedia/en/8/85/Terminator2poster.jpg",
      "director": "James Cameron",
      "actors": ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"],
      "imdb_point": 8.5,
  },
  {
      "name": "The Matrix",
      "img": "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
      "director": "The Wachowskis",
      "actors": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
      "imdb_point": 8.7,
  },
  {
      "name": "Minority Report",
      "img": "https://upload.wikimedia.org/wikipedia/en/4/44/Minority_Report_Poster.jpg",
      "director": "Steven Spielberg",
      "actors": ["Tom Cruise", "Colin Farrell", "Samantha Morton", "Max von Sydow"],
      "imdb_point": 7.6,
  },
  {
      "name": "Inception",
      "img": "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
      "director": "Christopher Nolan",
      "actors": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page", "Tom Hardy"],
      "imdb_point": 8.8,
  },
  {
      "name": "Arrival",
      "img": "https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg",
      "director": "Denis Villeneuve",
      "actors": ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
      "imdb_point": 8.0,
  },
  {
      "name": "Interstellar",
      "img": "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
      "director": "Christopher Nolan",
      "actors": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
      "imdb_point": 8.6,
  }, {
    "name": "Dune",
    "img": "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg",
    "director": "Denis Villeneuve",
    "actors": ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Josh Brolin"],
    "imdb_point": 8.1,
},
{
    "name": "Mad Max: Fury Road",
    "img": "https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg",
    "director": "George Miller",
    "actors": ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Rosie Huntington-Whiteley"],
    "imdb_point": 8.1,
},
{
    "name": "Ex Machina",
    "img": "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Ex-machina-uk-poster.jpg/330px-Ex-machina-uk-poster.jpg",
    "director": "Alex Garland",
    "actors": ["Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac", "Sonoya Mizuno"],
    "imdb_point": 7.7,
}]
